### PR TITLE
Scale BL jutsu with rank at half rate, restrict offense boost to highest

### PR DESCRIPTION
**Pull request by aumu1031**
Putting these suggestions here for your thoughts.

### CODE REVIEW

**Comment by aumu1031** [comment]
For BL jutsu at Jonin, using typical values:
- Genin: 2.5 -> 3.5 power
- Chuunin: 3.5 -> 3.95 power
- Jonin: 4.4 power

BL jutsu are typically not used except in BL builds, so this is expected to have no/low impact for majority of players.

Test case for boost stacking, typical balance build for Phantasmal Stalker at Jonin cap, jutsu lv100:

```T1 Nerve Destruction: Arthesia deals 24518.98 damage to Kibou Defector. -Kibou Defector takes 29422.77 residual damage-
Total: 53941

T1 Mental Vigor: 2 turns
T2 Nerve Destruction: Arthesia deals 43651.40 damage to Kibou Defector. -Kibou Defector takes 52381.68 residual damage-
Total: 96032

T1 Shards of Self: 3 turns
T2 Nerve Destruction: Arthesia deals 48073.13 damage to Kibou Defector. -Kibou Defector takes 57687.75 residual damage-
Total: 105760

T1 Shards of Self: 3 turns
T2 Mental Vigor: 2 turns
T3 Nerve Destruction: Arthesia deals 81338.04 damage to Kibou Defector. -Kibou Defector takes 97605.65 residual damage-
Total: 178943

T1 Mental Vigor: 2 turns
T2 Shards of Self: 3 turns
T3 Nerve Destruction: Arthesia deals 74093.22 damage to Kibou Defector. -Kibou Defector takes 88911.87 residual damage-
Total: 163004

T1 Mental Vigor: 2 turns
T2 Shards of Self: 3 turns
T3 Drowning Torrent: Arthesia deals 70154.94 damage to Kibou Defector. Kibou Defector's Taijutsu offense is being lowered. (70154.94 * 0.65% = 45600)```

With change such that only the highest boost applies:
```T1 Mental Vigor: 2 turns
T2 Shards of Self: 3 turns
T3 Nerve Destruction: Arthesia deals 54960.80 damage to Kibou Defector. -Kibou Defector takes 65952.96 residual damage-
Total: 120912```

```Factoring in change to BL jutsu such that lower rank jutsu scale at half rate:
T1 Mental Vigor: 2 turns
T2 Shards of Self: 3 turns
T3 Nerve Destruction: Arthesia deals 57987.51 damage to Kibou Defector. -Kibou Defector takes 69585.01 residual damage-
Total: 127,845```

Additional suggested change for speed boosting jutsu which are currently unused by players:
- Cast Speed no Jutsu
- Untouchable
Base Effect: 25% => 30% 
Effect lv100: 30% => 36%
Duration: 3 turns => 4 turns

Calculations used: https://docs.google.com/spreadsheets/d/19soHg1hBp9OiPLui4CU016eHVgW7_T8q9E0di5NyiWM/edit#gid=0
Tested on live server over course of 30m with help from capped players. General conclusions:
- Speed boost remains a poor choice for players with average speed
- Speed boost becomes a strong choice for players with high speed

**Comment by aumu1031** [comment]
Additional suggested change along with above.
For speed boosting jutsu which are currently unused by players:
- Cast Speed no Jutsu
- Untouchable
Base Effect: 25% => 30% 
Effect lv100: 30% => 36%
Duration: 3 turns => 4 turns

Calculations used: https://docs.google.com/spreadsheets/d/19soHg1hBp9OiPLui4CU016eHVgW7_T8q9E0di5NyiWM/edit#gid=0
Tested on live server over course of 30m with help from capped players. General conclusions:
- Speed boost remains a poor choice for players with average speed
- Speed boost becomes a strong choice for players with high speed

**Comment by levimeahan** [comment]
> For BL jutsu at Jonin, using typical values:
> 
>     * Genin: 2.5 -> 3.5 power
>     * Chuunin: 3.5 -> 3.95 power 
>     * Jonin: 4.4 power

I like this, let's do it

**Comment by levimeahan** [comment]
> Additional suggested change along with above. For speed boosting jutsu which are currently unused by players: Cast Speed no Jutsu & Untouchable
> 
>     * Base Effect: 25% => 30%
> 
>     * Duration: 3 turns => 4 turns

This sounds good but 4 turns is a long time for any effect to be active. What about 35-40% for 3 turns?

**Comment by aumu1031** [comment]
> 

Higher percent boost for speed is a little weird because it benefits players with lower speed more while causing players with high speed to overcap. Also I'm not 100% sure on how we can make the speed boost viable without increasing to 4 turns. Like if you get +20% evasion for 3 turns, that's still only 60% of an attack, and you sacrificed one of your own attacks to get it.

**Review by levimeahan — APPROVED** [review]

**Pull request merged**
