### PR TITLE
marriage

### PR DESCRIPTION
**Pull request by levimeahan**

### CODE REVIEW

**Review by levimeahan — COMMENTED** [review]
@MiteyDrill is this ready to go?

**Comment by MiteyDrill** [comment]
Not yet.

Still needs some testing, needs the ability to divorce, and the boost needs to be applied.

If users are okay with being married forever and no boost, then maybe the feature is ready.

Still need to test for multiple users proposing same time and what happens if someone accepts in-between someone else sending a proposal, a few bugs need to be stamped out

**Comment by MiteyDrill** [comment]
Added ability to divorce, tomorrow i'm gonna try to apply the marriage boost to regen. Not sure how i'm gonna add admin tools to marriage, gonna see...

I saw the Daily Task bar on user profile, looks amazing fr!

**Comment by HitoriWoB** [comment]
Still experiencing this issue/still working on it? Can try to help the best I can if it's on the error side.

**Pull request closed without merging**
