### PR TITLE
Mist tribe

### PR DESCRIPTION
**Pull request by TylerRedd**
Don't have to approve. But thought having the "Hold up" Vault Boy meme to go alongside the normal vault boy meme would be good.

### CODE REVIEW

**Comment by levimeahan** [comment]
Hmm can you find a colored version of this, since the existing one has the bold blue/yellow?

**Comment by TylerRedd** [comment]
I don't believe a colored one exists. The meme has always been black and
white. Like I said, you don't have to use it.

**Comment by levimeahan** [comment]
image
Can render this maybe

**Comment by TylerRedd** [comment]
Was actually in the process of it right now.

**Comment by TylerRedd** [comment]
That's the one I was working on. Don't think image from my email went through. Done, check it out. I resized and move the text a few times but it always came out too small. Scrapped it.

**Review by levimeahan — APPROVED** [review]
Perfect, let's do it!

**Pull request merged**
