### PR TITLE
Profile Page - Radial Graph for User Stats

### PR DESCRIPTION
**Pull request by MiteyDrill**
Radial Graph on profile page showcasing players current range of proficiency among skills - range exists between 1-5
image
image

### CODE REVIEW

**Comment by levimeahan** [comment]
Whoa, this is cool! Can we make it smaller though? My thought is we could drop the "Range of skill proficiency title" and make it smaller and put it here (in this screenshot I also changed the profile left/right columns from 50/50 to 45/55): 
image

**Comment by MiteyDrill** [comment]
Yeah that's a good idea I'll try putting it there

**Comment by MiteyDrill** [comment]
image
Position Updated

**Review by levimeahan — APPROVED** [review]

**Comment by MiteyDrill** [comment]
oops lol

**Pull request closed without merging**
