### PR TITLE
Arena kage

### PR DESCRIPTION
**Pull request by TylerRedd**
The Arena Kage is here!

### CODE REVIEW

**Comment by levimeahan** [comment]
LOL what's the context behind this one?

**Comment by TylerRedd** [comment]
Lmao because I always joke about becoming the Arenakage over at the
Underground Colosseum because I've been there for literal months now and
haven't left

**Comment by TylerRedd** [comment]
Lmao because I always joke about becoming Arenakage over at the Underground Colosseum because I've literally been there for months now without leaving.

**Review by levimeahan — APPROVED** [review]

**Comment by levimeahan** [comment]
LMAO let's do it

**Pull request merged**
