### PR TITLE
Survival missions now lock the user in battle

### PR DESCRIPTION
**Pull request by Kengetsu**
This will lock players in battle during survival missions preventing them from being attacked or accidentally moving without retreating.

### CODE REVIEW

**Comment by Kengetsu** [comment]
Still working on an inconvenience with the enter combat button. Once clicked you need to manually refresh the combat page for the next opponent to show.

**Comment by levimeahan** [comment]
Hmm before we merge this, I'm not sure it's desirable to allow users to spam survival mission repeatedly with no threat of being attacked. I'd be okay with blocking movement until the mission is done if you want to change it to that, but otherwise I need to give some design thought to survival missions

**Comment by Kengetsu** [comment]
That's actually what this is doing. It will lock them in combat with the previous AI. So they can't keep spamming AI and the mission doesn't progress until they press enter battle or retreat. It's meant as a way to prevent the user from doing anything else while they are "ambushed"

**Review by levimeahan — APPROVED** [review]
Oh I see, so they can't heal between fights. Okay, that makes more sense! Let's do it

**Pull request merged**
